version: '2'

volumes:
  code:

services:
  code:
    build:
      context: .
      dockerfile: Dockerfile
    image: aguaragazu/code-server-php:latest
    volumes:
      - /opt/jjsoft/docker-siges:/home/coder/project
      - /opt/jjsoft/code/local:/home/coder/.local
      - /opt/jjsoft/code/cache:/home/coder/.cache
    ports:
      - "8443:8443"
    environment:
      - PASSWORD=password
    command: --allow-http

