version: '3'

volumes:
  code:

services:
  code:
    build:
      context: .
      dockerfile: Dockerfile
    image: aguaragazu/code:latest
    volumes:
      - ./conf/coder-config.yaml:/home/coder/.config/code-server/config.yaml
      - ./project/index.php:/var/www/html/index.php
      - ./project:/home/coder/project
      - ./data/local:/home/coder/.local
      - ./data/cache:/home/coder/.cache
    ports:
      - 4200:4200
      - 8080:8080
      - 80:80
      - 443:443
  